# NumPy: slicing y broadcasting

En este notebook exploro cómo seleccionar datos y operar entre arrays
de distintas dimensiones usando NumPy.


In [4]:
import numpy as np

## arange()

Si quiero un array del tamaño "m", el argumento del .arange debe ser: 
.arange(a, m+1). 
Por ejemplo, quiero un array de tamaño 12:

In [5]:
A_00 = np.arange(1, 13)

In [6]:
A_00

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## reshape()

Ahora usaremos .reshape(). Lo que hace es redimensionar los datos: 
.reshape(nº filas, nº columnas) puedo crear y a la vez darle la estructura a un array

In [5]:
A_01 = np.arange(1, 7).reshape(3, 2)

In [6]:
A_01

array([[1, 2],
       [3, 4],
       [5, 6]])

o si ya tengo un array puedo redimencionarlo
por ejemplo: 
El array A_00 es un array 1x12 (1 fila, 12 columnas), 
con esto lo puedo tranformar en un array 3x4 (3 filas, 4 columnas)

In [38]:
A_00.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

el redimensionamiento no cambia el original, 
solo es una reestructuracion momentanea, segun se necesite.
Si quiero guardar la estructura del array debo guardarlo en otra variable

In [34]:
A_00_2x6 = A_00.reshape(2,6)

In [35]:
A_00

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
A_00_2x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Ahora existen ambas

# Slicing Basico

son cortes que le hacemos a un array
vamos a referenciar:
A: array
m: fila
n: columna
a: numero inicial
b: numero final

In [7]:
A_02 = np.arange(1,25).reshape(4,6)
A_02

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

## [:] Toda el array

In [8]:
A_02[:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

## [m] Solo una fila, cualquiera, segun el indice que se coloque en "m"

In [10]:
A_02[0]

array([1, 2, 3, 4, 5, 6])

In [11]:
A_02[1]

array([ 7,  8,  9, 10, 11, 12])

## [ : , : ] Todo el array, pero a partir de este formato, puedo empezar a elegir mas opciones

In [13]:
A_02[:,:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

## [ a:b , c:d ]  desde la fila "a" a la fila "b" y de la columna "c" a la "d"

In [32]:
A_02[0:4,0:6] # el array completo

# RECORDATORIO: los indices de principio y final del array entero
#               empiezan en 0 y terminan en n+1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [30]:
A_02[1:4,1:6] # el array -1ra fila, -1ra col

array([[ 8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24]])

In [33]:
A_02[2:4,1:5] # el array desde 2da fila, -1ra col -6ta columna

array([[14, 15, 16, 17],
       [20, 21, 22, 23]])

In [19]:
# [a:b, ] Solo algunas filas, de la a a la b, todas las columnas
# [ :b, ] Solo algunas filas, de la primera fila hasta b, todas las columnas
A_02[:2,]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
# Segunda columna (todas las filas, de la columna 1)
A_02[:, 0]

array([ 1,  7, 13, 19])

In [15]:
# Segunda columna (todas las filas, de la columna 2)
A_02[:, 1]

array([ 2,  8, 14, 20])

# Slicing con pasos

In [18]:
A_02

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [16]:
# Filas alternadas
A_02[::2]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [17]:
# Columnas desde la 2 en adelante
A_02[:, 2:]

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

# Broadcasting simple

In [21]:
A_02

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [20]:
A_02 + 10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [23]:
A_02 * 2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36],
       [38, 40, 42, 44, 46, 48]])

# Broadcasting con vector

In [48]:
A_02

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [49]:
v1 = np.array([1,10,100,1000,10000,100000])
A_02 + v1

array([[     2,     12,    103,   1004,  10005, 100006],
       [     8,     18,    109,   1010,  10011, 100012],
       [    14,     24,    115,   1016,  10017, 100018],
       [    20,     30,    121,   1022,  10023, 100024]])

In [50]:
A_02 * v1

array([[      1,      20,     300,    4000,   50000,  600000],
       [      7,      80,     900,   10000,  110000, 1200000],
       [     13,     140,    1500,   16000,  170000, 1800000],
       [     19,     200,    2100,   22000,  230000, 2400000]])

# Ejercicio 1: Normalizar cada columna

In [53]:
# Para visualizar y emprolijar la vision de los datos usaremos este comando
# Solo cambia cómo se muestran los datos (no los datos)
# No estamos redondeando ni truncando

np.set_printoptions(precision=3,suppress=True)

In [54]:
# promedio: promedia las columnas
# (axis=0): promedia columna por columna
means = A_02.mean(axis=0)
print("vector promedio: ", means)

vector promedio:  [10. 11. 12. 13. 14. 15.]


In [55]:
#Desviacion Estandar: que tan desviados estan los datos del promedio
stds = A_02.std(axis=0)
print(stds)

[6.708 6.708 6.708 6.708 6.708 6.708]


In [56]:
#Normmalizamos
A_02_norm = (A_02 - means) / stds
A_02_norm

array([[-1.342, -1.342, -1.342, -1.342, -1.342, -1.342],
       [-0.447, -0.447, -0.447, -0.447, -0.447, -0.447],
       [ 0.447,  0.447,  0.447,  0.447,  0.447,  0.447],
       [ 1.342,  1.342,  1.342,  1.342,  1.342,  1.342]])

In [39]:
A_02_norm_round = np.round(A_02_norm, 2)
A_02_norm_round

array([[-1.34, -1.34, -1.34, -1.34, -1.34, -1.34],
       [-0.45, -0.45, -0.45, -0.45, -0.45, -0.45],
       [ 0.45,  0.45,  0.45,  0.45,  0.45,  0.45],
       [ 1.34,  1.34,  1.34,  1.34,  1.34,  1.34]])